# Generated by Django 4.2.4 on 2026-08-30 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=50, unique=True)),
                ('is_details_added', models.BooleanField(default=False, null=True)),
                ('is_password_set', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.SmallIntegerField(null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='banner/')),
                ('describe', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.SmallIntegerField(null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_order_id', models.CharField(max_length=50, null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('is_amount_paid', models.BooleanField(null=True)),
                ('is_order_delivered', models.BooleanField(default=False, null=True)),
                ('is_order_cancaled', models.BooleanField(default=False, null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='product/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('is_favorite', models.SmallIntegerField(default=0, null=True)),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.mainmenus')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddrsss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_order_id', models.CharField(max_length=50, null=True)),
                ('payment_type', models.CharField(max_length=10, null=True)),
                ('balance_amt_due', models.FloatField(default=0.0, null=True)),
                ('original_amount', models.FloatField(default=0.0)),
                ('coupon_discount', models.FloatField(default=0.0, null=True)),
                ('net_amount', models.FloatField(default=0.0)),
                ('refund_amount', models.FloatField(default=0.0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('paymtent_status', models.CharField(default='Paid', max_length=50, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='domain.order')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_order_id', models.CharField(max_length=50, null=True)),
                ('payment_type', models.CharField(max_length=10, null=True)),
                ('payment_amount', models.CharField(max_length=50, null=True)),
                ('payment_gateway', models.CharField(max_length=40, null=True)),
                ('paytm_checksum', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.transactiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.mainmenus')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.submenus'),
        ),
        migrations.CreateModel(
            name='PayTMTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_order_id', models.CharField(max_length=50, null=True)),
                ('payment_type', models.CharField(max_length=10, null=True)),
                ('payment_amount', models.CharField(max_length=50, null=True)),
                ('token', models.CharField(max_length=500, null=True)),
                ('bank_name', models.CharField(max_length=500, null=True)),
                ('bank_txn_id', models.CharField(max_length=500, null=True)),
                ('checksum', models.CharField(max_length=500, null=True)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('gateway_name', models.CharField(max_length=50, null=True)),
                ('mid', models.CharField(max_length=100, null=True)),
                ('payment_mode', models.CharField(max_length=50, null=True)),
                ('response_code', models.CharField(max_length=50, null=True)),
                ('response_msg', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('txn_amount', models.CharField(max_length=50, null=True)),
                ('txn_date', models.DateTimeField(null=True)),
                ('txn_id', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='domain.order')),
                ('transaction_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='domain.transactiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField(null=True)),
                ('sub_total', models.FloatField(default=0.0, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Customizedesgin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(max_length=100, null=True)),
                ('moblie_no', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('attachment', models.ImageField(null=True, upload_to='customize/')),
                ('describe', models.CharField(max_length=500, null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.color')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.size')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(null=True)),
                ('review', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('prodcut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='domain.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField(null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.productvariant')),
            ],
        ),
    ]
